In [3]:
from torch import torch


def tensors_on_gpus():
    x = torch.zeros(32, 32)
    print(x)
    print(x.device)
    print(torch.device("mps"))
    print(torch.cuda.is_available())
    print(torch.cuda.device_count())
    print(torch.cuda.get_device_properties(0))


tensors_on_gpus()

tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])
cpu
mps
False
0


AssertionError: Torch not compiled with CUDA enabled

In [ ]:
def tensor_storage():
    x = torch.zeros(4, 3)
    print(x)
    r, c = 1, 2
    index = r * x.stride(0) + c * x.stride(1)
    print(index)


tensor_storage()

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
5


In [ ]:
def tensor_slicing():
    x = torch.tensor([[1, 2, 3], [4, 5, 6]])
    print(x[0])
    print(x[:, 0])
    print(x.view(3, 2))
    print(x.transpose(1, 0))


tensor_slicing()

tensor([1, 2, 3])
tensor([1, 4])
tensor([[1, 2],
        [3, 4],
        [5, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])


In [ ]:
B = 1024
D = 256
K = 64
x = torch.ones(B, D)
w = torch.randn(D, K)
y = x @ w
y
actual_num_flops = 2 * B * D * K

tensor([[  7.9543,  -2.9156, -21.8894,  ...,   5.3303,   6.0759,  10.1497],
        [  7.9543,  -2.9156, -21.8894,  ...,   5.3303,   6.0759,  10.1497],
        [  7.9543,  -2.9156, -21.8894,  ...,   5.3303,   6.0759,  10.1497],
        ...,
        [  7.9543,  -2.9156, -21.8894,  ...,   5.3303,   6.0759,  10.1497],
        [  7.9543,  -2.9156, -21.8894,  ...,   5.3303,   6.0759,  10.1497],
        [  7.9543,  -2.9156, -21.8894,  ...,   5.3303,   6.0759,  10.1497]])

In [11]:
def gradient():
    x = torch.tensor([1.0, 2, 3])
    w = torch.tensor([1.0, 1, 1], requires_grad=True)
    pred_y = x @ w

    loss = 0.5 * (pred_y - 5).pow(2)
    print(f"loss before backward: {loss}")
    print(f"loss.grad before backward: {loss.grad}")
    print(f"x.grad before backward: {x.grad}")
    print(f"pred_y.grad before backward: {pred_y.grad}")
    print(f"w.grad before backward: {w.grad}")
    loss.backward()
    print(f"loss after backward: {loss}")
    print(f"loss.grad after backward: {loss.grad}")
    print(f"x.grad after backward: {x.grad}")
    print(f"pred_y.grad after backward: {pred_y.grad}")
    print(f"w.grad after backward: {w.grad}")


gradient()

loss before backward: 0.5
loss.grad before backward: None
x.grad before backward: None
pred_y.grad before backward: None
w.grad before backward: None
loss after backward: 0.5
loss.grad after backward: None
x.grad after backward: None
pred_y.grad after backward: None
w.grad after backward: tensor([1., 2., 3.])


/var/folders/m3/ykw46t0n621bf438lng8x69w0000gn/T/ipykernel_80354/3445796865.py:8: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more information. (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/build/aten/src/ATen/core/TensorBody.h:499.)
  print(f"loss.grad before backward: {loss.grad}")
/var/folders/m3/ykw46t0n621bf438lng8x69w0000gn/T/ipykernel_80354/3445796865.py:10: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain